apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.dbAppName }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  serviceName: {{ .Values.dbAppName }}
  selector:
    matchLabels:
      app: {{ .Values.dbAppName }}
  template:
    metadata:
      labels:
        app: {{ .Values.dbAppName }}
    spec:   
      containers:
        - name: postgres
          image: postgres:12.0-alpine
          imagePullPolicy: {{ .Values.image.pullPolicy }}  
          ports:
            - containerPort: {{ .Values.databaseServicePort }}        
          env:
            - name: POSTGRES_DB
              value: {{ .Values.database.name }}
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secretName }}
                  key: {{ .Values.database.secretKey }}
            - name: POSTGRES_USER
              value: {{ .Values.database.user }}
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-db
      volumes:
          - name: postgres-db
            persistentVolumeClaim:
              claimName: {{ .Values.pvcName }}