apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.dbAppName }}
  name: {{ .Values.dbAppName }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: {{ .Values.databaseServicePortName }}
      port: {{ .Values.databaseServicePort }}
      targetPort: {{ .Values.databaseServicePort }}
  selector:
    app: {{ .Values.dbAppName }}
status:
  loadBalancer: {}