apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.fastapiName }}
  name: {{ .Values.fastapiName }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: {{ .Values.ingress.fastapi.portFastapiName }}
      port: {{ .Values.ingress.fastapi.portFastapi }}
      targetPort: {{ .Values.ingress.fastapi.portFastapi }}
  selector:
    app: {{ .Values.fastapiName }}
status:
  loadBalancer: {}