apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.hpaName }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.fastapiName }}
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70