apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.appName }}
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: {{ .Values.pgadminDeployment.defaultEmail }}
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.pgadminDeployment.secretName }}
                  key: {{ .Values.pgadminDeployment.secretKey }}
          image: {{ .Values.pgadminDeployment.image }}
          name: {{ .Values.appName }}
          ports:
            - containerPort: {{ .Values.pgadminDeployment.containerPort }}
              protocol: {{ .Values.pgadminDeployment.containerProtocol }}
      restartPolicy: {{ .Values.pgadminDeployment.restartPolicy }}