apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.appName}}
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: {{ .Values.pgadminService.pgadminServicePortName }}
      port: {{ .Values.pgadminService.pgadminServicePort }}
      targetPort: {{ .Values.pgadminService.pgadminTargetPort }}
  selector:
    app: {{ .Values.appName}}
status:
  loadBalancer: {}