appName: pgadmin-helm
fastapiName: fastapi
fastapiNodeport: fastapinodeport
hpaName: fastapi-hpa
namespace: helm
pvcName: postgres-pv-claim-helm
storageClassName: stclassname-helm
pvName: postgres-pv-helm
dbAppName: db
databaseServicePortName: "5432"
databaseServicePort: 5432

pgadminDeployment:
  defaultEmail: admin@admin.com
  secretName: postgresql-pgadmin-userpass
  secretKey: password
  password: cm9vdA==
  image: dpage/pgadmin4
  containerPort: 80
  containerProtocol: TCP
  restartPolicy: Always

pgadminService:
  pgadminServicePortName: "8080"
  pgadminServicePort: 8080
  pgadminTargetPort: 80

database:
  name: storedb
  secretName: postgresql-database-password
  secretKey: password
  user: admin
  password: cGFzc3dvcmQ=

image:
  name: vikinghacker/fastapi_app
  tag: "latest"
  pullPolicy: "IfNotPresent"

ingress:
  pgadmin:
    name: ingress-pgadmin
    pgadminHost: pgadmin.hackerblog.cloudns.ph
    className: traefik
    path: /
    pathType: Prefix
    port: 8080
  fastapi:
    nameFastapi: ingress-fastapi
    fastapiHost: hackerblog.cloudns.ph
    className: traefik
    pathFastapi: /
    pathUsersFastapi: /users
    pathUsersCountFastapi: /users/count
    pathTypeFastapi: Prefix
    portFastapiName: "5000"
    portFastapi: 5000
    protocol: TCP

tls:
  secretNamePgadmin: letsencrypt-prod
  secretNameFastapi: letsencrypt-prod2

clusterIssuerName: letsencrypt-prod 
